proxy:
  image: msereda/proxy:newest
  links:
    - identidock
  container_name: proxy 
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=192.168.0.11
    - NGINX_PROXY=http://identidock:9090
identidock:
  image: msereda/identidock:newest
  links:
    - dnmonster
    - redis
  environment:
    ENV: PROD
  container_name: identidock
dnmonster:
  image: amouat/dnmonster
  container_name: dnmonster
redis:
  image: redis
  container_name: redis
logspout:
  image: amouat/logspout-logstash
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "8000:80"
  container_name: logspout
  links:
    - logstash
  command: logstash://logstash:5000

logstash:
  image: logstash:7.0.0
  volumes:
    - ./logstash.conf:/etc/logstash.conf
  environment:
    LOGSPOUT: ignore
  command: -f /etc/logstash.conf
  container_name: logstash